### PR TITLE
Improving html2markdown

### PR DESCRIPTION
**Pull request by hgilani**
I was working on a html to markdown javascript implementation when you checked-in your project on github. Liked the idea of separate htmlparser that you were using and found a lot of similarities in my code with the way you were parsing. So I quickly merged my changes with you implementation, add added support for some other tags as well as some enhancements. 

We could merge the changes if you like to maintain one code base for html to markdown conversion in javascript. My changes might seem a lot for a pull request, feel free to ask any questions you have if you are accepting the pull request. I have added the unit test's in Jasmine all along, so it should be easy for you to test out the changes before accepting.

### CODE REVIEW

**Comment by kates** [comment]
Thanks. Let me find time to merge your changes.

**Comment by kates** [comment]
Hey @hgilani I'm putting this under MIT license. If you agree I'll add you as author and pull from your fork. Otherwise, I'll revert to the old version.

**Comment by hgilani** [comment]
Go ahead you can put this under MIT license and add me as author & pull from my fork.

**Comment by kates** [comment]
Thanks man. You've put more work in this than me.

**Pull request merged**
